### ISSUE TITLE
not work after build

### ISSUE THREAD

**Issue by Ending2015a** [blkcatman/SphericalImageCam_Free#1]
i just use default Main Camera with this script.
it works in unity edit mode, but dose not work after build.
what have i done wrong??
my unity version is 5.5.1f1 personal.
thanks~

**Comment by Ending2015a** [comment]
I got the error message:
WARNING: Shader Unsupported: 'Hidden/SphericalShader' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SphericalShader' - All passes removed
WARNING: Shader Unsupported: 'Hidden/SphericalShader' - Setting to default shader.

**Comment by blkcatman** [comment]
Hi Ending2015a,
What is a platform you choose to build?
I'll try to build in an environment similar to you.
Regards,

**Comment by Ending2015a** [comment]
local platform: windows 10 pro x64
build target: windows standalone x86 x64 both not work

**Comment by Ending2015a** [comment]
I found the solution
after I added spherical shader to  "Always Included Shaders"  in Settings -> Graphics 
it works~

**Comment by blkcatman** [comment]
Sorry for late reply.
Thank you for your report, new Unity version cannot find required shaders from a script even if the shader is added in Resource folder.
I'll fix this probrem soon.
Thank you!
